server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  
  # Do not cache index.html
  location = /index.html {
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
  }

  # Aggresive cache for hashed assets (i.e) index-B-FJGIbO.js
  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  # Short cache for icons
  location ~* \.(?:ico|png|svg)$ {
    expires 7d;
    add_header Cache-Control "public, must-revalidate";
  }

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
  }
}